puts "what a nutritious meal!"
puts "A plate of chicken"
p "A plate of Chicken\n"
 => "a plate of Chicken\n"
puts "with squash"
p "with squah\n"
 => "with squash\n"
puts "with eggplant"
p "with eggplant\n"
 => "with eggplant\n"